### PR TITLE
fix(itinerary-body): Add distances to access legs

### LINKED ISSUE #571: WALK + BIKE: add distance to turn instruction
In both OTP-UI and OTP-RR, the individual walk instructions lack a distance for how far to walk or bike.  A lack of distance in the walk instructions was pointed out as an issue in testing with sight-impaired folks.

Here's a visual of what OTP-UI is currently rendering:
Screenshot 2023-04-17 at 9 52 15 AM

Here's a picture of walk instructions with distance from an older (non OTP-UI) app:
Screenshot 2023-04-17 at 10 01 38 AM

NOTE: the distance information needs to make sense when read aloud by a screen reader (e.g., testing needed to come up with the proper wording, etc...).

### PR DESCRIPTION
**Pull request by miles-grant-ibigroup**
Close #571. This PR adds distances to each walking leg step. Styles are configurable in that the styled components can be overridden. If we want explicit prop-based configuration, that can be added.

Screenshot 2023-04-28 at 1 11 27 PM

### CODE REVIEW

**Review by fpurcell — APPROVED** [review]
Hey Miles ... looks good.  (And bonus points that it renders also in the print itinerary).

File: packages/itinerary-body/src/styled.tsx [hunk 1]
```diff
@@ -594,6 +594,12 @@ export const StepStreetName = styled.span`
   font-weight: 500;
 `;
 
+export const StepLength = styled.span`
+  font-weight: 200;
+  opacity: 0.8;
```
Comment (amy-corson-ibigroup) [inline packages/itinerary-body/src/styled.tsx:599]: Color contrast is getting flagged here.  Maybe keep the opacity at 100%, and instead use `|` to provide some separation in the line? So it would read:
Left on Pioneer Sq N (path) | 22 feet | (Mapillary Btn)

**Review by amy-corson-ibigroup — COMMENTED** [review]
Looks really nice! Approved pending this small color contrast issue.

File: packages/itinerary-body/src/styled.tsx (hunk 1 above)
Comment (miles-grant-ibigroup) [reply packages/itinerary-body/src/styled.tsx:599]: Ugh that's really annoying... I initially had the `|` but it looks really really messy. Can we get away with 0.9?

Comment (amy-corson-ibigroup) [reply packages/itinerary-body/src/styled.tsx:599]: .9 does pass! Visually I'm not sure there's clear distinction between the opacities though. Maybe an `-` instead of `|`? or would that have the same issue?

Comment (miles-grant-ibigroup) [reply packages/itinerary-body/src/styled.tsx:599]: I think that's even more confusing... Let me find the lowest opacity that still passes AA. Or are we targeting AAA?

Comment (amy-corson-ibigroup) [reply packages/itinerary-body/src/styled.tsx:599]: Nope AA is fine! I think it'd be somewhere between `.8` and `.9`

Comment (miles-grant-ibigroup) [reply packages/itinerary-body/src/styled.tsx]: `0.8975` 😵‍💫 (fbb2294ee85649a3b1d9ee3fec22da917411e9bb)

**Review by amy-corson-ibigroup — APPROVED** [review]
0.8975 it is! If I'm being aggressively nitpicky I'd say let's either just go with .9 or maybe add a comment saying why the number is _so_ specific, but ultimately I'll leave it up to you!
